Code refactoring

diff --git a/simon b/simon
--- a/simon
+++ b/simon
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 ### BEGIN INIT INFO
 # Provides:          simon 
 # Required-Start:   
@@ -9,21 +9,24 @@
 # Short-Description: Start/stop simon web server
 ### END INIT INFO
 
+. /lib/lsb/init-functions
 
 SYS_CHECK=/opt/simon/simon.sh
-
-test -f /opt/simon/simon.sh || exit
+test -f /opt/simon/simon.sh || echo -e "\e[1;31msimin.sh not found in /opt/simon\e[0m"; exit
 
 case "$1" in
 start)
         /opt/simon/simon.sh &
+		log_daemon_msg "Starting scripts" "simon"
     ;;
 stop)
         PID=`ps -C simon.sh -opid=`
         kill $PID
+		log_daemon_msg "Stoping scripts" "simon"
         ;;
 restart)
         $0 stop
     	$0 start
+		log_daemon_msg "Restarting scripts" "simon"
     ;;
 esac
